apiVersion: v1
kind: Pod
metadata:
  name: testpod
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: wn
  containers:
  - name: busybox
    image: busybox:1.28
    command: ["sh", "-c", "sleep 3600"]
  restartPolicy: Never
